# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(default=None, max_length=4, null=True)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('year', models.PositiveIntegerField(default=None, null=True)),
                ('owner', models.CharField(default=None, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=32, verbose_name='Бренд автомобіля')),
            ],
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default=None, max_length=32, verbose_name='Марка автомобіля')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='automobile.AutoBrand'),
        ),
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='automobile.AutoModel'),
        ),
    ]
